# Generated by Django 2.0.7 on 2018-07-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_styleimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleimage',
            name='image',
            field=models.ImageField(upload_to='style_image/'),
        ),
    ]
