# Generated by Django 2.0.7 on 2018-07-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_auto_20180724_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleimage',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
