# Generated by Django 2.0.7 on 2018-07-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricemenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemenu',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
