# Generated by Django 2.0.7 on 2018-07-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricemenu', '0002_auto_20180727_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemenu',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
