# Generated by Django 2.0.7 on 2018-07-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricemenu', '0003_auto_20180727_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricemenu',
            name='pricemenu_image',
            field=models.ImageField(null=True, upload_to='pricemenu_image/'),
        ),
    ]
