# Generated by Django 2.0.7 on 2018-07-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('menu', models.CharField(choices=[('cut', 'cut'), ('make', 'make'), ('color', 'color')], max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
