# Generated by Django 2.0.7 on 2018-07-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20180724_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_time',
            field=models.CharField(choices=[('1', '10-12'), ('2', '12-14'), ('3', '14-16'), ('4', '16-20')], max_length=50, null=True),
        ),
    ]
