# Generated by Django 2.0.7 on 2018-07-28 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricemenu', '0003_auto_20180727_0316'),
        ('booking', '0005_auto_20180724_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='menu',
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pricemenu.PriceMenu'),
        ),
    ]
