# Generated by Django 2.0.7 on 2018-07-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20180728_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='menu',
        ),
    ]
