# Generated by Django 2.0.7 on 2018-07-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='image',
            new_name='image_post',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='time',
            new_name='timestamp',
        ),
    ]
