# Generated by Django 2.0.7 on 2018-07-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180729_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image_post',
            field=models.ImageField(null=True, upload_to='image_post/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
