# Generated by Django 2.0.7 on 2018-07-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title_comment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
